# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend
    
    services: 
      mongodb:
        image: mongo:4.4.6
        ports: 
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm install --global jest
      
      - name: Run server.js
        run: node server.js

      - run: npm test