# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm install --global jest

      - name: Set up MongoDB
        uses: docker://mongo:4.4.6
        with:
          mongodb-version: '4.4.6'

      - name: Start MongoDB
        run: mongod --fork --logpath /tmp/mongodb.log

      - name: Run server.js
        run: node server.js
           
      - run: npm test